name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name daenamu-test --region ap-northeast-2

      - name: Deploy Istio Base
        run: helm upgrade --install istio-base istio/base -n istio-system --create-namespace -f daenamu2/Istio-values.yaml

      - name: Deploy Istiod
        run: helm upgrade --install istiod istio/istiod -n istio-system -f daenamu2/Istio-values.yaml

      - name: Deploy Jaeger
        run: helm upgrade --install jaeger jaegertracing/jaeger -n istio-system -f daenamu2/jaeger-values.yaml

      - name: Deploy Prometheus
        run: helm upgrade --install prometheus prometheus-community/prometheus -n istio-system -f daenamu2/prometheus-values.yaml

      - name: Deploy Karpernter
        run: helm upgrade --install karpenter karpenter/karpenter -n karpenter -f daenamu2/karpenter-values.yaml

      - name: Deploy Grafana
        run: helm upgrade --install grafana grafana/grafana -n istio-system -f daenamu2/grafana.yaml
