global:
  proxy:
    autoInject: enabled
  istioNamespace: istio-system

meshConfig:
  enablePrometheusMerge: true

pilot:
  traceSampling: 100.0
  resources:
    requests:
      cpu: 250m
      memory: 1Gi

gateways:
  istio-ingressgateway:
    enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
