## 더미컨텐츠
## nginx가 읽어 보여줄 index.html을 담은 kubernets 구성파일
## 실제로는 파일이 아니고 쿠버네티스 리소스로 html코드를 담아두는 형식
## pod가 부팅되면 이걸 /usr/share/nginx/html로 마운트해서 서빙함 (임시 리소스)

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>It works!</title></head>
    <body><h1>Hello from Istio NGINX!</h1></body>
    </html>