apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 30
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium"]
    - key: "kubernetes.io/os"
      operator: In
      values: ["linux"]
  limits:
    resources:
      cpu: "1000"
  provider:
    subnetSelector:
      karpenter.sh/discovery: daenamu-test
    securityGroupSelector:
      kubernetes.io/cluster/daenamu-test: "owned"
    instanceProfile: daenamu-test-node-group-instance-profile
